version: "3.8"

services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: smalluser
      POSTGRES_PASSWORD: smallpass
      POSTGRES_DB: smallrestaurant
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: test
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=smallrestaurant;Username=smalluser;Password=smallpass"
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "80:80"

volumes:
  db_data:
    driver: local
  pgadmin_data:
    driver: local
